name: Setup pnpm
description: Setup Node.js and pnpm with caching
inputs:
  node-version:
    description: Node.js version
    required: true
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Verify pnpm installation
      shell: bash
      run: |
        pnpm --version
        echo "PNPM_PATH=$(which pnpm)" >> $GITHUB_ENV
        if ! command -v pnpm &> /dev/null; then
          echo "pnpm not found in PATH" >&2
          exit 1
        fi

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
